/**
 * Icon Library - Maps icon names to Material Design Icons
 */
import {
  mdiServer,
  mdiRouterNetwork,
  mdiDatabase,
  mdiPowerSocket,
  mdiPowerSocketUs,
  mdiPowerSocketEu,
  mdiPowerSocketUk,
  mdiPowerPlug,
  mdiServerNetwork,
  mdiApi,
  mdiApplicationBraces,
  mdiNetworkOutline,
  mdiCubeOutline,
  mdiServerPlus,
  mdiServerMinus,
  mdiServerSecurity,
  mdiCloudOutline,
  mdiCog,
  mdiMemory,
  mdiArrowExpandVertical,
  mdiEthernet,
  mdiEthernetCable,
  mdiTable,
  mdiTableRow,
  mdiTableColumn,
  mdiHarddisk,
  mdiLanConnect,
  mdiLanPending,
  mdiPowerPlugOutline,
  mdiUsb,
  mdiHdmiPort,
  mdiVideoInputHdmi,
  mdiMicroSd,
  mdiUsbCPort,
  mdiLaserPointer,
  mdiIp,
  mdiWeb,
  mdiCodeBraces,
  mdiQrcode,
  mdiKey,
  mdiKeyboard,
  mdiMouse,
  mdiPrinter,
  mdiScanner,
  mdiSpeaker,
  mdiBarcode,
  mdiDoor,
  mdiTestTube,
  mdiCarBattery,
  mdiWifi,
  mdiAccessPoint,
  mdiBluetooth,
  mdiFolder,
  mdiFolderKey,
  mdiFolderKeyNetwork,
  mdiOfficeBuilding,
  mdiWallFire,
  mdiDisc,
  mdiApps,
  mdiAccount,
  mdiAccountMultiple,
  mdiEmoticon,
  mdiExpansionCard,
  mdiExpansionCardVariant,
  mdiNas,
  mdiApplication,
  mdiPackage,
  mdiPackageVariant,
  mdiPackageVariantClosed,
  mdiEngine,
  mdiCheckboxIntermediate,
  mdiDesktopTower,
  mdiCircleBox,
  mdiHexadecimal,
  mdiFridgeIndustrial,
  mdiThermometer,
  mdiMessageAlert,
  mdiMessage,
  mdiEmail,
  mdiProtocol,
  mdiWebhook,
  mdiGauge,
  mdiVolumeHigh,
  mdiFileDocument,
  mdiFile,
  mdiBucket,
  mdiAccountBox,
  mdiAccountGroup,
  mdiAccountSupervisor,
  mdiCardAccountDetails,
  mdiSitemap,
  mdiArrowUp,
  mdiArrowDown,
  mdiArrowLeft,
  mdiArrowRight,
  mdiFormTextbox,
  mdiFormDropdown,
  mdiFormTextarea,
  mdiCamera,
  mdiWebcam,
  mdiCctv,
  mdiMonitor,
  mdiPhone,
  mdiMonitorDashboard,
  mdiButtonCursor,
  mdiSignalCellular3,
  mdiPlay,
  mdiStop,
  mdiAlarmLight,
  mdiEye,
  mdiHandFrontRight,
  mdiAccountVoice,
  mdiEarHearing,
  mdiEmoticonTongue,
  mdiScent,
  mdiBrain,
  mdiFood,
  mdiPuzzle,
  mdiArmFlex,
  mdiChip,
  mdiSourceRepository,
  mdiFileCode,
  mdiLock,
  mdiShield,
  mdiArrowDecision,
  mdiLockOpen,
  mdiRouter,
  mdiRoutes,
  mdiEmailFast,
  mdiTimer,
  mdiDatabaseClock,
  mdiTimerSand,
  mdiRabbit,
  mdiAtom,
  mdiAtomVariant,
  mdiBeaker,
  mdiDna,
  mdiFlask,
  mdiScale,
  mdiFaceAgent,
  mdiCurrencyGbp,
  mdiCurrencyUsd,
  mdiCash,
  mdiHandshake,
  mdiBriefcaseAccount,
  mdiAccountPlus,
  mdiInvoice,
  mdiInvoiceList,
  mdiWebBox,
  mdiGridLarge,
  mdiBriefcase,
  mdiCalendarCheck,
  mdiFileTree,
  mdiTicket,
  mdiHeadset,
  mdiCommentQuestion,
  mdiFlag,
  mdiCity,
  mdiDomain,
  mdiTools,
  mdiFactory,
  mdiFan,
  mdiHeatPump,
  mdiHvac,
  mdiWaterBoiler,
  mdiDesk,
  mdiBiohazard,
  mdiFaceMask,
  mdiSafetyGoggles,
  mdiStairs,
  mdiNote,
  mdiNoteText,
  mdiFilter,
  mdiTableFilter,
  mdiFormatListGroup,
  mdiFunction,
  mdiFunctionVariant,
  mdiTrayArrowDown,
  mdiTrayArrowUp,
  mdiTrayFull,
  mdiTrayMinus,
  mdiTrayPlus,
  mdiTray,
  mdiCounter,
  mdiDatabasePlus,
  mdiDatabaseMinus,
  mdiDatabaseRemove,
  mdiDatabaseEdit,
  mdiDatabaseLock,
  mdiDatabaseRefresh,
  mdiDatabaseSync,
  mdiDatabaseCheck,
  mdiDatabaseSearch,
  mdiDatabaseExport,
  mdiDatabaseImport,
  mdiFileDelimited,
  mdiSetAll,
  mdiSetCenter,
  mdiSetCenterRight,
  mdiSetLeftCenter,
  mdiAlphaPBox,
  mdiZipBox,
  mdiSync,
  mdiCodeJson,
  mdiSelectGroup,
  mdiFileSend,
  mdiChartBar, 
  mdiChartGantt,
  mdiChartLine,
  mdiChartPie,
  mdiChartScatterPlot,
  mdiChartBarStacked,
  mdiChartHistogram,
  mdiChartBellCurve,
  mdiChartTimelineVariant,
  mdiGraph,
  mdiChartArc,
  mdiChartBubble,
  mdiCalculator,
  mdiCalculatorVariant,
  mdiRadioTower,
} from '@mdi/js'

/**
 * Icon registry - maps simple names to MDI icon paths
 */
export const iconRegistry = {
  // Server & Infrastructure
  'server': mdiServer,
  'rack': mdiServer, // Using server icon for rack
  'server-rack': mdiServer,
  'server-network': mdiServerNetwork,
  'server-plus': mdiServerPlus,
  'server-minus': mdiServerMinus,
  'server-security': mdiServerSecurity,
  'desktop-tower': mdiDesktopTower,
  
  // Network
  'switch': mdiRouterNetwork,
  'network': mdiNetworkOutline,
  'router': mdiRouterNetwork,
  'ethernet': mdiEthernet,
  'ethernet-cable': mdiEthernetCable,
  'cable': mdiEthernetCable,
  'lan-cable': mdiLanConnect,
  'fiber': mdiLanPending,
  'fiber-cable': mdiLanPending,
  'wall-fire': mdiWallFire,
  'wifi': mdiWifi,
  'access-point': mdiAccessPoint,
  'bluetooth': mdiBluetooth,
  'signal-cellular-3': mdiSignalCellular3,
  'radio-tower': mdiRadioTower,

  // Storage & Data
  'database': mdiDatabase,
  'storage': mdiCubeOutline,
  'table': mdiTable,
  'table-row': mdiTableRow,
  'table-column': mdiTableColumn,
  'folder': mdiFolder,
  'harddisk': mdiHarddisk,
  'microsd': mdiMicroSd,
  'folder-key': mdiFolderKey,
  'folder-key-network': mdiFolderKeyNetwork,
  'nas': mdiNas,
  'hexadecimal': mdiHexadecimal,
  'file-document': mdiFileDocument,
  'file': mdiFile,
  'bucket': mdiBucket,
  'chip': mdiChip,
  'source-repository': mdiSourceRepository,

  // Power
  'pdu': mdiPowerSocket,
  'power-socket-us': mdiPowerSocketUs,
  'power-socket-eu': mdiPowerSocketEu,
  'power-socket-uk': mdiPowerSocketUk,
  'power-plug': mdiPowerPlug,
  'power-cable': mdiPowerPlugOutline,
  
  // USB & Connectors
  'usb': mdiUsb,
  'usb-cable': mdiUsb,
  'hdmi': mdiHdmiPort,
  'hdmi-cable': mdiVideoInputHdmi,
  'usb-c-port': mdiUsbCPort,
  'laser-pointer': mdiLaserPointer,

  // Services & Software
  'api': mdiApi,
  'api-service': mdiApi,
  'application': mdiApplication,
  'cloud': mdiCloudOutline,
  'cog': mdiCog,
  'ip': mdiIp,
  'web': mdiWeb,
  'code-braces': mdiCodeBraces,
  'disc': mdiDisc,
  'apps': mdiApps,
  'application-braces': mdiApplicationBraces,
  'account': mdiAccount,
  'account-multiple': mdiAccountMultiple,
  'emoticon': mdiEmoticon,
  'package': mdiPackage,
  'package-variant': mdiPackageVariant,
  'package-variant-closed': mdiPackageVariantClosed,
  'engine': mdiEngine,
  'checkbox-intermediate': mdiCheckboxIntermediate,
  
  // Hardware
  'memory': mdiMemory,
  'component': mdiCubeOutline,
  'rack-unit': mdiArrowExpandVertical,
  'expansion-card': mdiExpansionCard,
  'expansion-card-variant': mdiExpansionCardVariant,

  // Physical
  'physical': mdiCubeOutline,
  'office-building': mdiOfficeBuilding,
  'door': mdiDoor,
  'test-tube': mdiTestTube,
  'car-battery': mdiCarBattery,
  'qrcode': mdiQrcode,
  'key': mdiKey,
  'keyboard': mdiKeyboard,
  'mouse': mdiMouse,
  'printer': mdiPrinter,
  'scanner': mdiScanner,
  'speaker': mdiSpeaker,
  'barcode': mdiBarcode,
  'circle-box': mdiCircleBox,
  'fridge-industrial': mdiFridgeIndustrial,
  'thermometer': mdiThermometer,

  // Alerts, Notifications, Messages, and Comms
  'message-alert': mdiMessageAlert,
  'message': mdiMessage,
  'email': mdiEmail,
  'protocol': mdiProtocol,
  'webhook': mdiWebhook,
  'gauge': mdiGauge,
  'volume-high': mdiVolumeHigh,

  // Business and People
  'person': mdiAccount,
  'account-box': mdiAccountBox,
  'account-group': mdiAccountGroup,
  'account-supervisor': mdiAccountSupervisor,
  'card-account-details': mdiCardAccountDetails,
  'sitemap': mdiSitemap,
  'arrow-up': mdiArrowUp,
  'arrow-down': mdiArrowDown,
  'arrow-left': mdiArrowLeft,
  'arrow-right': mdiArrowRight,
  'form-textbox': mdiFormTextbox,
  'form-dropdown': mdiFormDropdown,
  'form-textarea': mdiFormTextarea,
  'camera': mdiCamera,
  'webcam': mdiWebcam,
  'cctv': mdiCctv,
  'monitor': mdiMonitor,
  'monitor-dashboard': mdiMonitorDashboard,
  'phone': mdiPhone,
  'button-cursor': mdiButtonCursor,
  'play': mdiPlay,
  'stop': mdiStop,
  'alarm-light': mdiAlarmLight,
  'eye': mdiEye,
  'hand-front-right': mdiHandFrontRight,
  'account-voice': mdiAccountVoice,
  'ear-hearing': mdiEarHearing,
  'emoticon-tongue': mdiEmoticonTongue,
  'scent': mdiScent,
  'brain': mdiBrain,
  'food': mdiFood,
  'puzzle': mdiPuzzle,
  'arm-flex': mdiArmFlex,
  'file-code': mdiFileCode,
  'lock': mdiLock,
  'shield': mdiShield,
  'arrow-decision': mdiArrowDecision,
  'lock-open': mdiLockOpen,
  'router-alt': mdiRouter,
  'routes': mdiRoutes,
  'email-fast': mdiEmailFast,
  'timer': mdiTimer,
  'database-clock': mdiDatabaseClock,
  'timer-sand': mdiTimerSand,
  'rabbit': mdiRabbit,
  'atom': mdiAtom,
  'atom-variant': mdiAtomVariant,
  'beaker': mdiBeaker,
  'dna': mdiDna,
  'flask': mdiFlask,
  'scale': mdiScale,
  'face-agent': mdiFaceAgent,
  'currency-gbp': mdiCurrencyGbp,
  'currency-usd': mdiCurrencyUsd,
  'cash': mdiCash,
  'handshake': mdiHandshake,
  'briefcase-account': mdiBriefcaseAccount,
  'account-plus': mdiAccountPlus,
  'invoice': mdiInvoice,
  'invoice-list': mdiInvoiceList,
  'web-box': mdiWebBox,
  'grid-large': mdiGridLarge,
  'briefcase': mdiBriefcase,
  'calendar-check': mdiCalendarCheck,
  'file-tree': mdiFileTree,
  'ticket': mdiTicket,
  'headset': mdiHeadset,
  'comment-question': mdiCommentQuestion,
  'flag': mdiFlag,
  'city': mdiCity,
  'domain': mdiDomain,
  'tools': mdiTools,
  'factory': mdiFactory,
  'fan': mdiFan,
  'heat-pump': mdiHeatPump,
  'hvac': mdiHvac,
  'water-boiler': mdiWaterBoiler,
  'desk': mdiDesk,
  'biohazard': mdiBiohazard,
  'face-mask': mdiFaceMask,
  'safety-goggles': mdiSafetyGoggles,
  'stairs': mdiStairs,
  'note': mdiNote,
  'note-text': mdiNoteText,

  // Data Processing
  'filter': mdiFilter,
  'table-filter': mdiTableFilter,
  'format-list-group': mdiFormatListGroup,
  'function': mdiFunction,
  'function-variant': mdiFunctionVariant,
  'tray-arrow-down': mdiTrayArrowDown,
  'tray-arrow-up': mdiTrayArrowUp,
  'tray-full': mdiTrayFull,
  'tray-minus': mdiTrayMinus,
  'tray-plus': mdiTrayPlus,
  'tray': mdiTray,
  'counter': mdiCounter,
  'database-plus': mdiDatabasePlus,
  'database-minus': mdiDatabaseMinus,
  'database-remove': mdiDatabaseRemove,
  'database-edit': mdiDatabaseEdit,
  'database-lock': mdiDatabaseLock,
  'database-refresh': mdiDatabaseRefresh,
  'database-sync': mdiDatabaseSync,
  'database-check': mdiDatabaseCheck,
  'database-search': mdiDatabaseSearch,
  'database-export': mdiDatabaseExport,
  'database-import': mdiDatabaseImport,
  'file-delimited': mdiFileDelimited,
  'set-all': mdiSetAll,
  'set-center': mdiSetCenter,
  'set-center-right': mdiSetCenterRight,
  'set-left-center': mdiSetLeftCenter,
  'alpha-p-box': mdiAlphaPBox,
  'zip-box': mdiZipBox,
  'sync': mdiSync,
  'code-json': mdiCodeJson,
  'select-group': mdiSelectGroup,
  'file-send': mdiFileSend,
  'calculator': mdiCalculator,
  'calculator-variant': mdiCalculatorVariant,

  // Data Viz
  'chart-bar': mdiChartBar,
  'chart-gantt': mdiChartGantt,
  'chart-line': mdiChartLine,
  'chart-pie': mdiChartPie,
  'chart-scatter': mdiChartScatterPlot,
  'chart-bar-stacked': mdiChartBarStacked,
  'chart-histogram': mdiChartHistogram,
  'chart-bell-curve': mdiChartBellCurve,
  'chart-timeline-variant': mdiChartTimelineVariant,
  'graph': mdiGraph,
  'chart-arc': mdiChartArc,
  'chart-bubble': mdiChartBubble,
}

/**
 * Get icon path by name
 * @param {string} iconName - The icon name (e.g., 'server', 'database')
 * @returns {string|null} - The SVG path data or null if not found
 */
export function getIconPath(iconName) {
  if (!iconName) return null
  return iconRegistry[iconName.toLowerCase()] || null
}

/**
 * Check if an icon exists
 * @param {string} iconName - The icon name
 * @returns {boolean}
 */
export function hasIcon(iconName) {
  return iconName && iconRegistry.hasOwnProperty(iconName.toLowerCase())
}

/**
 * Get all available icon names
 * @returns {string[]}
 */
export function getAvailableIcons() {
  return Object.keys(iconRegistry)
}

